dataset_rootpath: /data-nas/data/experiments/zhenqing/HunyuanWorld-Voyager/examples/spatialvideo_test
test_split_file: /data-nas/data/dataset/open_source/RealEstate10K/DFoT_processed_data/datasets/real-estate-10k/test_256_150/process_re10k_wan_vace_data/metadata_wan_funcontrol_captioned.csv
checkpoint_path: /data-nas/data/experiments/zhenqing/DiffSynth-Studio/experiments/20260216_002751_functrl_14Blora_depthcat_mixed_256/step-4000.safetensors
depth_concat_type: width_wise
finetune_mode: lora
video_size: 256
wan_version: 14B

owner: zhenqing
task_script: test_voyager_on_spatialvideo.py
task_name: spatialvideo-voyager-infer
resources:
  gpus: 1
  cpu: 22
  memory: 100Gi

seed: 0

env:
  image: registry.qunhequnhe.com/mri/trellis:metaquery
  sync_mode: git
  data: "alluxio-alluxio-csi-fuse-pvc:/alluxio"
  data_dir: /data-nas:/data-nas
  data_high_dir: /data-high-nas:/data-high-nas
  sync_source: https://gitlab.qunhequnhe.com/zhenqing/Spatial3DV.git
  sync_branch: develop
  gpu_card: 4090D
  cpu_size: 112
  selector: user=zhenqing

parallel:
  jobs: 8
  task_id: 0
  exclude:
  include:
  workers: 8


output:
  path: /data-nas/data/experiments/zhenqing/HunyuanWorld-Voyager/results_spatialvideo
  format: txt
  overwrite: true
